// AUTO-GENERATED from ~/Dev/configs/menus/ (via menus.py build-catalog)
// Edit the source yaml; this file is regenerated by scripts/sync-catalog.py.

export interface CatalogSubPage { label: string; path: string }
export interface CatalogLink { label: string; url: string }
export interface CatalogEntry {
  id: string
  type:
    | 'subdomain' | 'vps-only' | 'tool-lib' | 'raycast-wrapper'
    | 'config-repo' | 'knowledge' | 'app-candidate' | 'archived' | 'dormant'
  name?: string
  subdomain?: string
  url?: string
  port?: number
  access_type?: 'public' | 'cf-access'
  group?: string
  description?: string
  source?: string
  path?: string
  stack?: string[]
  status?: string
  sub_pages?: CatalogSubPage[]
  links?: CatalogLink[]
}

export const CATALOG = ({
  "meta": {
    "generated_at": "2026-04-19T10:05:21",
    "sources": [
      "~/Dev/website/lib/services.ts",
      "~/Dev/configs/menus/sites/*.yaml",
      "~/Dev/configs/menus/navbar.yaml"
    ]
  },
  "entries": [
    {
      "id": "sub:tianlizeng.cloud",
      "type": "subdomain",
      "name": "曾田力",
      "subdomain": "tianlizeng.cloud",
      "url": "https://tianlizeng.cloud",
      "access_type": "public",
      "group": "主站",
      "description": "个人网站 — 水利工程师 / AI 工程师 / 独立开发者",
      "source": "website",
      "path": "~/Dev/website",
      "sub_pages": [
        {
          "label": "关于我",
          "path": "/about"
        },
        {
          "label": "作品",
          "path": "/projects"
        },
        {
          "label": "研究",
          "path": "/research"
        },
        {
          "label": "博客",
          "path": "/blog"
        },
        {
          "label": "生活",
          "path": "/life"
        },
        {
          "label": "服务",
          "path": "/services"
        }
      ]
    },
    {
      "id": "sub:hydro",
      "type": "subdomain",
      "name": "Hydro Toolkit",
      "subdomain": "hydro",
      "url": "https://hydro.tianlizeng.cloud",
      "access_type": "public",
      "group": "水利工具",
      "description": "水利计算工具集主平台，插件式集成多个计算模块",
      "port": 8510,
      "source": "hydro-toolkit",
      "path": "~/Dev/hydro-toolkit"
    },
    {
      "id": "sub:hydro-annual",
      "type": "subdomain",
      "name": "水资源年报",
      "subdomain": "hydro-annual",
      "url": "https://hydro-annual.tianlizeng.cloud",
      "access_type": "public",
      "group": "水利工具",
      "description": "浙江省水资源年报查询，按地区年份筛选导出",
      "port": 8514,
      "source": "hydro-annual",
      "path": "~/Dev/hydro-annual"
    },
    {
      "id": "sub:hydro-capacity",
      "type": "subdomain",
      "name": "纳污能力",
      "subdomain": "hydro-capacity",
      "url": "https://hydro-capacity.tianlizeng.cloud",
      "access_type": "public",
      "group": "水利工具",
      "description": "河流/水库纳污能力计算，支持分段与多方案对比",
      "port": 8511,
      "source": "hydro-capacity",
      "path": "~/Dev/hydro-capacity"
    },
    {
      "id": "sub:hydro-district",
      "type": "subdomain",
      "name": "河区调度",
      "subdomain": "hydro-district",
      "url": "https://hydro-district.tianlizeng.cloud",
      "access_type": "public",
      "group": "水利工具",
      "description": "浙东河区调度模型，水平衡与分水枢纽计算",
      "port": 8516,
      "source": "hydro-district",
      "path": "~/Dev/hydro-district"
    },
    {
      "id": "sub:hydro-efficiency",
      "type": "subdomain",
      "name": "水效评估",
      "subdomain": "hydro-efficiency",
      "url": "https://hydro-efficiency.tianlizeng.cloud",
      "access_type": "public",
      "group": "水利工具",
      "description": "工业集聚区水效评估（AHP+CRITIC+TOPSIS）",
      "port": 8513,
      "source": "hydro-efficiency",
      "path": "~/Dev/hydro-efficiency"
    },
    {
      "id": "sub:hydro-geocode",
      "type": "subdomain",
      "name": "地理编码",
      "subdomain": "hydro-geocode",
      "url": "https://hydro-geocode.tianlizeng.cloud",
      "access_type": "public",
      "group": "水利工具",
      "description": "经纬度/地址互转与企业搜索（高德 API）",
      "port": 8517,
      "source": "hydro-geocode",
      "path": "~/Dev/hydro-geocode"
    },
    {
      "id": "sub:hydro-irrigation",
      "type": "subdomain",
      "name": "灌溉需水",
      "subdomain": "hydro-irrigation",
      "url": "https://hydro-irrigation.tianlizeng.cloud",
      "access_type": "public",
      "group": "水利工具",
      "description": "灌溉需水量计算，上传数据计算并导出",
      "port": 8515,
      "source": "hydro-irrigation",
      "path": "~/Dev/hydro-irrigation"
    },
    {
      "id": "sub:hydro-rainfall",
      "type": "subdomain",
      "name": "降雨径流",
      "subdomain": "hydro-rainfall",
      "url": "https://hydro-rainfall.tianlizeng.cloud",
      "access_type": "public",
      "group": "水利工具",
      "description": "概湖灌溉需水量计算（降雨径流 ETL 管线）",
      "port": 8518,
      "source": "hydro-rainfall",
      "path": "~/Dev/hydro-rainfall"
    },
    {
      "id": "sub:hydro-reservoir",
      "type": "subdomain",
      "name": "水库群调度",
      "subdomain": "hydro-reservoir",
      "url": "https://hydro-reservoir.tianlizeng.cloud",
      "access_type": "public",
      "group": "水利工具",
      "description": "梯级水库群发电调度，参数配置与结果可视化",
      "port": 8512,
      "source": "hydro-reservoir",
      "path": "~/Dev/hydro-reservoir"
    },
    {
      "id": "sub:hydro-risk",
      "type": "subdomain",
      "name": "风险图数据",
      "subdomain": "hydro-risk",
      "url": "https://hydro-risk.tianlizeng.cloud",
      "access_type": "public",
      "group": "水利工具",
      "description": "洪水风险图数据表填充（GeoJSON 三阶段 ETL）",
      "port": 8519,
      "source": "hydro-risk",
      "path": "~/Dev/hydro-risk"
    },
    {
      "id": "sub:dashboard",
      "type": "subdomain",
      "name": "Repo Dashboard",
      "subdomain": "dashboard",
      "url": "https://dashboard.tianlizeng.cloud",
      "access_type": "public",
      "group": "开发与 AI",
      "description": "项目控制台 — VPS 服务/任务/Git 提交总览",
      "port": 8520,
      "source": "ops-console",
      "path": "~/Dev/ops-console",
      "sub_pages": [
        {
          "label": "概览",
          "path": "/"
        },
        {
          "label": "Auggie 索引",
          "path": "/auggie"
        },
        {
          "label": "Hammerspoon",
          "path": "/hammerspoon"
        }
      ]
    },
    {
      "id": "sub:cclog",
      "type": "subdomain",
      "name": "CC 会话日志",
      "subdomain": "cclog",
      "url": "https://cclog.tianlizeng.cloud",
      "access_type": "public",
      "group": "开发与 AI",
      "description": "CC 会话历史仪表盘，按项目/日期/关键词筛选",
      "port": 8898,
      "source": "cclog",
      "path": "~/Dev/cclog"
    },
    {
      "id": "sub:changelog",
      "type": "subdomain",
      "name": "CC Changelog",
      "subdomain": "changelog",
      "url": "https://changelog.tianlizeng.cloud",
      "access_type": "public",
      "group": "开发与 AI",
      "description": "CC 自我进化系统变更日志，按阶段展示演进记录",
      "source": "cc-evolution",
      "path": "~/Dev/cc-evolution"
    },
    {
      "id": "sub:dockit",
      "type": "subdomain",
      "name": "Dockit",
      "subdomain": "dockit",
      "url": "https://dockit.tianlizeng.cloud",
      "access_type": "public",
      "group": "开发与 AI",
      "description": "文档处理工具箱 — Word/PPT/Excel 多格式处理",
      "port": 8503,
      "source": "dockit",
      "path": "~/Dev/dockit"
    },
    {
      "id": "sub:stack",
      "type": "subdomain",
      "name": "Stack",
      "subdomain": "stack",
      "url": "https://stack.tianlizeng.cloud",
      "access_type": "cf-access",
      "group": "开发与 AI",
      "description": "~/Dev 项目架构说明书",
      "source": "stack",
      "path": "~/Dev/stack",
      "sub_pages": [
        {
          "label": "水利工具",
          "path": "#水利工具"
        },
        {
          "label": "开发工具",
          "path": "#开发工具"
        },
        {
          "label": "CC 生态",
          "path": "#CC 生态"
        },
        {
          "label": "Web 服务",
          "path": "#Web 服务"
        },
        {
          "label": "桌面与配置",
          "path": "#桌面与配置"
        },
        {
          "label": "知识与内容",
          "path": "#知识与内容"
        },
        {
          "label": "投资与 AI",
          "path": "#投资与 AI"
        },
        {
          "label": "基础设施",
          "path": "#基础设施"
        },
        {
          "label": "归档候选",
          "path": "#归档候选"
        }
      ]
    },
    {
      "id": "sub:cmds",
      "type": "subdomain",
      "name": "CC Docs",
      "subdomain": "cmds",
      "url": "https://cmds.tianlizeng.cloud",
      "access_type": "cf-access",
      "group": "开发与 AI",
      "description": "CC 命令 & 技能说明书",
      "source": "cmds",
      "path": "~/Dev/cmds",
      "sub_pages": [
        {
          "label": "部署",
          "path": "#部署"
        },
        {
          "label": "CC 生态",
          "path": "#CC 生态"
        },
        {
          "label": "Repo 治理",
          "path": "#Repo 治理"
        },
        {
          "label": "文档处理",
          "path": "#文档处理"
        },
        {
          "label": "水利专业",
          "path": "#水利专业"
        },
        {
          "label": "杂项",
          "path": "#杂项"
        }
      ]
    },
    {
      "id": "sub:journal",
      "type": "subdomain",
      "name": "Journal",
      "subdomain": "journal",
      "url": "https://journal.tianlizeng.cloud",
      "access_type": "cf-access",
      "group": "开发与 AI",
      "description": "HANDOFF / 方案 / 复盘时间线",
      "source": "journal",
      "path": "~/Dev/journal"
    },
    {
      "id": "sub:playbooks",
      "type": "subdomain",
      "name": "Playbooks",
      "subdomain": "playbooks",
      "url": "https://playbooks.tianlizeng.cloud",
      "access_type": "cf-access",
      "group": "开发与 AI",
      "description": "工作方法论 × 命令映射 — 标书/生态流量/再生水",
      "source": "playbooks",
      "path": "~/Dev/playbooks"
    },
    {
      "id": "sub:cc-options",
      "type": "subdomain",
      "name": "QQQ CC Dashboard",
      "subdomain": "cc-options",
      "url": "https://cc-options.tianlizeng.cloud",
      "access_type": "cf-access",
      "group": "投资工具",
      "description": "QQQ Covered Call 期权交易仪表盘",
      "port": 8521,
      "source": "international-assets",
      "path": "~/Dev/international-assets"
    },
    {
      "id": "sub:docs",
      "type": "subdomain",
      "name": "知识库",
      "subdomain": "docs",
      "url": "https://docs.tianlizeng.cloud",
      "access_type": "cf-access",
      "group": "内容与媒体",
      "description": "Knowledge Dashboard — 文档/指南/知识检索",
      "source": "docs",
      "path": "~/Dev/docs"
    },
    {
      "id": "sub:audiobook",
      "type": "subdomain",
      "name": "有声书",
      "subdomain": "audiobook",
      "url": "https://audiobook.tianlizeng.cloud",
      "access_type": "public",
      "group": "内容与媒体",
      "description": "Markdown 转有声书，多音色选择与句级同步",
      "port": 9200,
      "source": "audiobook",
      "path": "~/Dev/audiobook"
    },
    {
      "id": "sub:status",
      "type": "vps-only",
      "name": "Uptime Kuma",
      "subdomain": "status",
      "url": "https://status.tianlizeng.cloud",
      "access_type": "cf-access",
      "group": "基础设施",
      "description": "服务可用性监控",
      "port": 3001
    },
    {
      "id": "sub:n8n",
      "type": "vps-only",
      "name": "n8n",
      "subdomain": "n8n",
      "url": "https://n8n.tianlizeng.cloud",
      "access_type": "cf-access",
      "group": "基础设施",
      "description": "工作流自动化引擎",
      "port": 5678
    },
    {
      "id": "sub:panel",
      "type": "vps-only",
      "name": "Marzban",
      "subdomain": "panel",
      "url": "https://panel.tianlizeng.cloud",
      "access_type": "public",
      "group": "基础设施",
      "description": "代理面板管理",
      "port": 8000
    },
    {
      "id": "sub:sub",
      "type": "vps-only",
      "name": "Marzban 订阅",
      "subdomain": "sub",
      "url": "https://sub.tianlizeng.cloud",
      "access_type": "public",
      "group": "基础设施",
      "description": "代理客户端订阅端点",
      "port": 8000
    },
    {
      "id": "sub:proxy",
      "type": "subdomain",
      "name": "OAuth Proxy",
      "subdomain": "proxy",
      "url": "https://proxy.tianlizeng.cloud",
      "access_type": "cf-access",
      "group": "基础设施",
      "description": "Cloudflare Access 认证代理",
      "port": 9100,
      "source": "oauth-proxy",
      "path": "~/Dev/oauth-proxy"
    },
    {
      "id": "sub:webhook",
      "type": "vps-only",
      "name": "Webhook",
      "subdomain": "webhook",
      "url": "https://webhook.tianlizeng.cloud",
      "access_type": "public",
      "group": "基础设施",
      "description": "GitHub Webhook 接收器",
      "port": 9000
    },
    {
      "id": "local:cc-configs",
      "type": "tool-lib",
      "name": "cc-configs",
      "path": "~/Dev/cc-configs",
      "links": [
        {
          "label": "GitHub",
          "url": "https://github.com/zengtianli/cc-configs"
        }
      ]
    },
    {
      "id": "local:devtools",
      "type": "tool-lib",
      "name": "devtools",
      "path": "~/Dev/devtools",
      "links": [
        {
          "label": "GitHub",
          "url": "https://github.com/zengtianli/devtools"
        }
      ]
    },
    {
      "id": "local:doctools",
      "type": "tool-lib",
      "name": "doctools",
      "path": "~/Dev/doctools",
      "links": [
        {
          "label": "GitHub",
          "url": "https://github.com/zengtianli/doctools"
        }
      ]
    },
    {
      "id": "local:mactools",
      "type": "tool-lib",
      "name": "mactools",
      "path": "~/Dev/mactools",
      "links": [
        {
          "label": "GitHub",
          "url": "https://github.com/zengtianli/mactools"
        }
      ]
    },
    {
      "id": "local:clashx",
      "type": "tool-lib",
      "name": "clashx",
      "path": "~/Dev/clashx",
      "links": [
        {
          "label": "GitHub",
          "url": "https://github.com/zengtianli/clashx"
        }
      ]
    },
    {
      "id": "local:hydro-apps",
      "type": "tool-lib",
      "name": "hydro-apps",
      "path": "~/Dev/hydro-apps",
      "links": [
        {
          "label": "GitHub",
          "url": "https://github.com/zengtianli/hydro-apps"
        }
      ]
    },
    {
      "id": "local:hydro-qgis",
      "type": "tool-lib",
      "name": "hydro-qgis",
      "path": "~/Dev/hydro-qgis",
      "links": [
        {
          "label": "GitHub",
          "url": "https://github.com/zengtianli/hydro-qgis"
        }
      ]
    },
    {
      "id": "local:downloads-organizer",
      "type": "tool-lib",
      "name": "downloads-organizer",
      "path": "~/Dev/downloads-organizer",
      "links": [
        {
          "label": "GitHub",
          "url": "https://github.com/zengtianli/downloads-organizer"
        }
      ]
    },
    {
      "id": "local:dockit-raycast",
      "type": "raycast-wrapper",
      "name": "dockit-raycast",
      "path": "~/Dev/dockit-raycast",
      "links": [
        {
          "label": "GitHub",
          "url": "https://github.com/zengtianli/dockit-raycast"
        }
      ]
    },
    {
      "id": "local:raycast",
      "type": "raycast-wrapper",
      "name": "raycast",
      "path": "~/Dev/raycast",
      "links": [
        {
          "label": "GitHub",
          "url": "https://github.com/zengtianli/raycast"
        }
      ]
    },
    {
      "id": "local:configs",
      "type": "config-repo",
      "name": "configs",
      "path": "~/Dev/configs",
      "links": [
        {
          "label": "GitHub",
          "url": "https://github.com/zengtianli/configs"
        }
      ]
    },
    {
      "id": "local:dotfiles",
      "type": "config-repo",
      "name": "dotfiles",
      "path": "~/Dev/dotfiles",
      "links": [
        {
          "label": "GitHub",
          "url": "https://github.com/zengtianli/dotfiles"
        }
      ]
    },
    {
      "id": "local:essays",
      "type": "knowledge",
      "name": "essays",
      "path": "~/Dev/essays",
      "links": [
        {
          "label": "GitHub",
          "url": "https://github.com/zengtianli/essays"
        }
      ]
    },
    {
      "id": "local:learn",
      "type": "knowledge",
      "name": "learn",
      "path": "~/Dev/learn",
      "links": [
        {
          "label": "GitHub",
          "url": "https://github.com/zengtianli/learn"
        }
      ]
    },
    {
      "id": "local:vps",
      "type": "knowledge",
      "name": "vps",
      "path": "~/Dev/vps",
      "links": [
        {
          "label": "GitHub",
          "url": "https://github.com/zengtianli/vps"
        }
      ]
    },
    {
      "id": "local:resume",
      "type": "knowledge",
      "name": "resume",
      "path": "~/Dev/resume",
      "links": [
        {
          "label": "GitHub",
          "url": "https://github.com/zengtianli/resume"
        }
      ]
    },
    {
      "id": "local:llm-finetune",
      "type": "app-candidate",
      "name": "llm-finetune",
      "path": "~/Dev/llm-finetune",
      "links": [
        {
          "label": "GitHub",
          "url": "https://github.com/zengtianli/llm-finetune"
        }
      ]
    },
    {
      "id": "local:mindmap",
      "type": "app-candidate",
      "name": "mindmap",
      "path": "~/Dev/mindmap",
      "links": [
        {
          "label": "GitHub",
          "url": "https://github.com/zengtianli/mindmap"
        }
      ]
    },
    {
      "id": "local:cockpit",
      "type": "app-candidate",
      "name": "cockpit",
      "path": "~/Dev/cockpit",
      "links": [
        {
          "label": "GitHub",
          "url": "https://github.com/zengtianli/cockpit"
        }
      ]
    },
    {
      "id": "local:scripts",
      "type": "archived",
      "name": "scripts",
      "path": "~/Dev/scripts",
      "links": [
        {
          "label": "GitHub",
          "url": "https://github.com/zengtianli/scripts"
        }
      ]
    },
    {
      "id": "local:scripts-archive",
      "type": "archived",
      "name": "scripts-archive",
      "path": "~/Dev/scripts-archive",
      "links": [
        {
          "label": "GitHub",
          "url": "https://github.com/zengtianli/scripts-archive"
        }
      ]
    },
    {
      "id": "local:analysis-hermes-vs-mine",
      "type": "archived",
      "name": "analysis-hermes-vs-mine",
      "path": "~/Dev/analysis-hermes-vs-mine",
      "links": [
        {
          "label": "GitHub",
          "url": "https://github.com/zengtianli/analysis-hermes-vs-mine"
        }
      ]
    },
    {
      "id": "local:hammerspoon",
      "type": "dormant",
      "name": "hammerspoon",
      "path": "~/Dev/hammerspoon",
      "links": [
        {
          "label": "GitHub",
          "url": "https://github.com/zengtianli/hammerspoon"
        }
      ]
    }
  ]
}) as {
  meta: { generated_at: string; sources: string[] }
  entries: CatalogEntry[]
}
