// AUTO-GENERATED from ~/Dev/tools/configs/menus/sites/website.yaml
// Edit the yaml; this file is regenerated by scripts/sync-menu.py (prebuild hook).

export const navigationConfig = [
  { name: "关于我", path: "/about" },
  { name: "作品", path: "/projects" },
  { name: "研究", path: "/research" },
  { name: "博客", path: "/blog" },
  { name: "生活", path: "/life" },
]
