// AUTO-GENERATED from ~/Dev/tools/configs/menus/entities/* + relations/subdomain-group.yaml
// Regenerate via: python3 ~/Dev/devtools/lib/tools/menus.py build-services-ts -w
// Do NOT edit this file directly — edits are clobbered on next render.

export interface ServiceConfig {
  name: string
  subdomain: string
  description: string
  url?: string
  port?: number
  accessType?: 'public' | 'cf-access'
}

export interface ServiceGroupConfig {
  title: string
  icon: string
  color: string
  services: ServiceConfig[]
}

export const DOMAIN = 'tianlizeng.cloud'

export const SERVICE_GROUPS: ServiceGroupConfig[] = [
  {
    title: "主站",
    icon: "globe",
    color: "text-[#1d1d1f]",
    services: [
      { name: "曾田力", subdomain: "tianlizeng.cloud", description: "个人网站 — 水利工程师 / AI 工程师 / 独立开发者", url: "https://tianlizeng.cloud" },
    ],
  },
  {
    title: "水利工具",
    icon: "droplets",
    color: "text-blue-600",
    services: [
      { name: "Hydro Toolkit", subdomain: "hydro", description: "水利计算工具集主平台，插件式集成多个计算模块", port: 8510 },
      { name: "水资源年报", subdomain: "hydro-annual", description: "浙江省水资源年报查询，按地区年份筛选导出", port: 8514 },
      { name: "纳污能力", subdomain: "hydro-capacity", description: "河流/水库纳污能力计算，支持分段与多方案对比", port: 8511 },
      { name: "河区调度", subdomain: "hydro-district", description: "浙东河区调度模型，水平衡与分水枢纽计算", port: 8516 },
      { name: "水效评估", subdomain: "hydro-efficiency", description: "工业集聚区水效评估（AHP+CRITIC+TOPSIS）", port: 8513 },
      { name: "地理编码", subdomain: "hydro-geocode", description: "经纬度/地址互转与企业搜索（高德 API）", port: 8517 },
      { name: "灌溉需水", subdomain: "hydro-irrigation", description: "灌溉需水量计算，上传数据计算并导出", port: 8515 },
      { name: "降雨径流", subdomain: "hydro-rainfall", description: "概湖灌溉需水量计算（降雨径流 ETL 管线）", port: 8518 },
      { name: "水库群调度", subdomain: "hydro-reservoir", description: "梯级水库群发电调度，参数配置与结果可视化", port: 8512 },
      { name: "风险图数据", subdomain: "hydro-risk", description: "洪水风险图数据表填充（GeoJSON 三阶段 ETL）", port: 8519 },
    ],
  },
  {
    title: "开发与 AI",
    icon: "code2",
    color: "text-purple-600",
    services: [
      { name: "Repo Dashboard", subdomain: "dashboard", description: "项目控制台 — VPS 服务/任务/Git 提交总览", port: 8520 },
      { name: "CC 会话日志", subdomain: "cclog", description: "CC 会话历史仪表盘，按项目/日期/关键词筛选", port: 8898 },
      { name: "Logs", subdomain: "logs", description: "HANDOFF / 方案 / 复盘 / CC 进化 — 统一时间线", accessType: "cf-access" },
      { name: "Dockit", subdomain: "dockit", description: "文档处理工具箱 — Word/PPT/Excel 多格式处理", port: 8503 },
      { name: "Stack", subdomain: "stack", description: "~/Dev 项目架构说明书", accessType: "cf-access" },
      { name: "CC Docs", subdomain: "cmds", description: "CC 命令 & 技能说明书", accessType: "cf-access" },
      { name: "Playbooks", subdomain: "playbooks", description: "工作方法论 × 命令映射 — 标书/生态流量/再生水", accessType: "cf-access" },
    ],
  },
  {
    title: "投资工具",
    icon: "trending-up",
    color: "text-green-600",
    services: [
      { name: "理财笔记", subdomain: "assets", description: "国际资产配置公开笔记 — 换汇 / 投资 / 香港银行 / 策略分析" },
      { name: "QQQ CC Dashboard", subdomain: "cc-options", description: "QQQ Covered Call 期权交易仪表盘", port: 8521, accessType: "cf-access" },
    ],
  },
  {
    title: "内容与媒体",
    icon: "book-open",
    color: "text-amber-600",
    services: [
      { name: "知识库", subdomain: "docs", description: "Knowledge Dashboard — 文档/指南/知识检索", accessType: "cf-access" },
      { name: "有声书", subdomain: "audiobook", description: "Markdown 转有声书，多音色选择与句级同步", port: 9200 },
    ],
  },
  {
    title: "基础设施",
    icon: "shield",
    color: "text-gray-600",
    services: [
      { name: "Uptime Kuma", subdomain: "status", description: "服务可用性监控", port: 3001, accessType: "cf-access" },
      { name: "n8n", subdomain: "n8n", description: "工作流自动化引擎", port: 5678, accessType: "cf-access" },
      { name: "Marzban", subdomain: "panel", description: "代理面板管理", port: 8000 },
      { name: "Marzban 订阅", subdomain: "sub", description: "代理客户端订阅端点", port: 8000 },
      { name: "OAuth Proxy", subdomain: "proxy", description: "Cloudflare Access 认证代理", port: 9100, accessType: "cf-access" },
      { name: "Webhook", subdomain: "webhook", description: "GitHub Webhook 接收器", port: 9000 },
    ],
  },
]
