// AUTO-GENERATED from ~/Dev/tools/configs/menus/navbar.yaml (R7.2 unified light mega)
// Edit the yaml; this file is regenerated by menus.py build-website-navbar
// (or via website prebuild hook).

export interface MegaItem { label: string; url: string; key?: string; access?: 'cf-access' }
export interface MegaGroup { title: string; items: MegaItem[] }
export interface MegaCategory {
  key: string
  label: string
  columns: MegaGroup[][]   // 长度恒为 4（可含空数组占位），统一浅灰
}
export interface SharedBrand { label: string; url: string; key: string }

export const SHARED_BRAND: SharedBrand = {"label": "曾田力", "url": "https://tianlizeng.cloud/", "key": "home"}

export const MEGA_CATEGORIES: MegaCategory[] = [
  {
    "key": "home",
    "label": "🏠 主站",
    "columns": [
      [
        {
          "title": "关于",
          "items": [
            {
              "label": "关于我",
              "url": "https://tianlizeng.cloud/about",
              "key": "about"
            },
            {
              "label": "作品",
              "url": "https://tianlizeng.cloud/projects",
              "key": "projects"
            },
            {
              "label": "研究",
              "url": "https://tianlizeng.cloud/research",
              "key": "research"
            },
            {
              "label": "博客",
              "url": "https://tianlizeng.cloud/blog",
              "key": "blog"
            },
            {
              "label": "生活",
              "url": "https://tianlizeng.cloud/life",
              "key": "life"
            }
          ]
        }
      ],
      [
        {
          "title": "入口",
          "items": [
            {
              "label": "服务总览",
              "url": "https://tianlizeng.cloud/services",
              "key": "services"
            },
            {
              "label": "Stack",
              "url": "https://stack.tianlizeng.cloud",
              "key": "stack"
            },
            {
              "label": "CC Docs",
              "url": "https://cmds.tianlizeng.cloud",
              "key": "cmds",
              "access": "cf-access"
            },
            {
              "label": "Dashboard",
              "url": "https://dashboard.tianlizeng.cloud",
              "key": "dashboard"
            },
            {
              "label": "Auggie",
              "url": "https://dashboard.tianlizeng.cloud/auggie",
              "key": "auggie"
            },
            {
              "label": "搜索",
              "url": "https://tianlizeng.cloud/search",
              "key": "search"
            }
          ]
        }
      ],
      [],
      []
    ]
  },
  {
    "key": "hydro",
    "label": "💧 水利",
    "columns": [
      [
        {
          "title": "主平台",
          "items": [
            {
              "label": "Hydro Toolkit",
              "url": "https://hydro.tianlizeng.cloud",
              "key": "hydro"
            }
          ]
        }
      ],
      [
        {
          "title": "水资源/调度",
          "items": [
            {
              "label": "水资源年报",
              "url": "https://hydro-annual.tianlizeng.cloud",
              "key": "hydro-annual"
            },
            {
              "label": "水库群调度",
              "url": "https://hydro-reservoir.tianlizeng.cloud",
              "key": "hydro-reservoir"
            },
            {
              "label": "河区调度",
              "url": "https://hydro-district.tianlizeng.cloud",
              "key": "hydro-district"
            }
          ]
        }
      ],
      [
        {
          "title": "评估/编码",
          "items": [
            {
              "label": "水效评估",
              "url": "https://hydro-efficiency.tianlizeng.cloud",
              "key": "hydro-efficiency"
            },
            {
              "label": "地理编码",
              "url": "https://hydro-geocode.tianlizeng.cloud",
              "key": "hydro-geocode"
            },
            {
              "label": "纳污能力",
              "url": "https://hydro-capacity.tianlizeng.cloud",
              "key": "hydro-capacity"
            }
          ]
        }
      ],
      [
        {
          "title": "风险/降雨",
          "items": [
            {
              "label": "风险图数据",
              "url": "https://hydro-risk.tianlizeng.cloud",
              "key": "hydro-risk"
            },
            {
              "label": "降雨径流",
              "url": "https://hydro-rainfall.tianlizeng.cloud",
              "key": "hydro-rainfall"
            },
            {
              "label": "灌溉需水",
              "url": "https://hydro-irrigation.tianlizeng.cloud",
              "key": "hydro-irrigation"
            }
          ]
        }
      ]
    ]
  },
  {
    "key": "dev",
    "label": "🛠 开发",
    "columns": [
      [
        {
          "title": "子域服务",
          "items": [
            {
              "label": "Repo Dashboard",
              "url": "https://dashboard.tianlizeng.cloud",
              "key": "dashboard"
            },
            {
              "label": "CC 会话日志",
              "url": "https://cclog.tianlizeng.cloud",
              "key": "cclog"
            },
            {
              "label": "Logs",
              "url": "https://logs.tianlizeng.cloud",
              "key": "logs",
              "access": "cf-access"
            },
            {
              "label": "Dockit",
              "url": "https://dockit.tianlizeng.cloud",
              "key": "dockit"
            },
            {
              "label": "Stack",
              "url": "https://stack.tianlizeng.cloud",
              "key": "stack",
              "access": "cf-access"
            },
            {
              "label": "CC Docs",
              "url": "https://cmds.tianlizeng.cloud",
              "key": "cmds",
              "access": "cf-access"
            },
            {
              "label": "Playbooks",
              "url": "https://playbooks.tianlizeng.cloud",
              "key": "playbooks",
              "access": "cf-access"
            }
          ]
        }
      ],
      [
        {
          "title": "工具库",
          "items": [
            {
              "label": "cc-configs",
              "url": "https://github.com/zengtianli/cc-configs",
              "key": "cc-configs"
            },
            {
              "label": "devtools",
              "url": "https://github.com/zengtianli/devtools",
              "key": "devtools"
            },
            {
              "label": "doctools",
              "url": "https://github.com/zengtianli/doctools",
              "key": "doctools"
            },
            {
              "label": "mactools",
              "url": "https://github.com/zengtianli/mactools",
              "key": "mactools"
            },
            {
              "label": "clashx",
              "url": "https://github.com/zengtianli/clashx",
              "key": "clashx"
            }
          ]
        }
      ],
      [
        {
          "title": "Raycast / 配置",
          "items": [
            {
              "label": "raycast",
              "url": "https://github.com/zengtianli/raycast",
              "key": "raycast"
            },
            {
              "label": "configs",
              "url": "https://github.com/zengtianli/configs",
              "key": "configs"
            }
          ]
        }
      ],
      []
    ]
  },
  {
    "key": "content",
    "label": "📚 内容",
    "columns": [
      [
        {
          "title": "日志 / 知识",
          "items": [
            {
              "label": "Logs",
              "url": "https://logs.tianlizeng.cloud",
              "key": "logs",
              "access": "cf-access"
            },
            {
              "label": "知识库",
              "url": "https://docs.tianlizeng.cloud",
              "key": "docs",
              "access": "cf-access"
            },
            {
              "label": "有声书",
              "url": "https://audiobook.tianlizeng.cloud",
              "key": "audiobook"
            },
            {
              "label": "CC 会话",
              "url": "https://cclog.tianlizeng.cloud",
              "key": "cclog"
            },
            {
              "label": "Playbooks",
              "url": "https://playbooks.tianlizeng.cloud",
              "key": "playbooks",
              "access": "cf-access"
            }
          ]
        }
      ],
      [
        {
          "title": "投资",
          "items": [
            {
              "label": "理财笔记",
              "url": "https://assets.tianlizeng.cloud",
              "key": "assets"
            },
            {
              "label": "QQQ CC Dashboard",
              "url": "https://cc-options.tianlizeng.cloud",
              "key": "cc-options",
              "access": "cf-access"
            }
          ]
        }
      ],
      [],
      []
    ]
  },
  {
    "key": "infra",
    "label": "⚙️ 基础设施",
    "columns": [
      [
        {
          "title": "监控 / 自动化",
          "items": [
            {
              "label": "Uptime Kuma",
              "url": "https://status.tianlizeng.cloud",
              "key": "status",
              "access": "cf-access"
            },
            {
              "label": "n8n",
              "url": "https://n8n.tianlizeng.cloud",
              "key": "n8n",
              "access": "cf-access"
            }
          ]
        }
      ],
      [
        {
          "title": "代理",
          "items": [
            {
              "label": "OAuth Proxy",
              "url": "https://proxy.tianlizeng.cloud",
              "key": "proxy",
              "access": "cf-access"
            },
            {
              "label": "Marzban",
              "url": "https://panel.tianlizeng.cloud",
              "key": "panel"
            },
            {
              "label": "Marzban 订阅",
              "url": "https://sub.tianlizeng.cloud",
              "key": "sub"
            }
          ]
        }
      ],
      [
        {
          "title": "WEBHOOK",
          "items": [
            {
              "label": "Webhook",
              "url": "https://webhook.tianlizeng.cloud",
              "key": "webhook"
            }
          ]
        }
      ],
      []
    ]
  }
]

export const SHARED_NO_CURRENT_HOSTS: string[] = ["hammerspoon.tianlizeng.cloud", "auggie.tianlizeng.cloud", "audiobook.tianlizeng.cloud", "proxy.tianlizeng.cloud"]

export const SHARED_CURRENT_HOST_MAP: Record<string, string> = {"stack.tianlizeng.cloud": "home", "cmds.tianlizeng.cloud": "home", "dashboard.tianlizeng.cloud": "dev", "logs.tianlizeng.cloud": "content", "docs.tianlizeng.cloud": "content", "audiobook.tianlizeng.cloud": "content", "cclog.tianlizeng.cloud": "content", "playbooks.tianlizeng.cloud": "content", "cc-options.tianlizeng.cloud": "content", "assets.tianlizeng.cloud": "content", "status.tianlizeng.cloud": "infra", "n8n.tianlizeng.cloud": "infra", "panel.tianlizeng.cloud": "infra", "sub.tianlizeng.cloud": "infra", "webhook.tianlizeng.cloud": "infra"}
