#!/usr/bin/env python3
"""website 主导航同步：sites/website.yaml → lib/menu.generated.ts

由 prebuild / predev hook 触发；也可手动跑：
  python3 scripts/sync-menu.py

SSOT：~/Dev/configs/menus/sites/website.yaml
消费者：lib/profile-config.ts re-exports navigationConfig from './menu.generated'
"""
import json
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("ERROR: 需要 PyYAML。安装：pip3 install pyyaml", file=sys.stderr)
    sys.exit(2)

REPO = Path(__file__).parent.parent
YAML = Path.home() / "Dev" / "configs" / "menus" / "sites" / "website.yaml"
OUT = REPO / "lib" / "menu.generated.ts"


def main():
    if not YAML.exists():
        print(f"ERROR: {YAML} not found", file=sys.stderr)
        sys.exit(1)
    cfg = yaml.safe_load(YAML.read_text(encoding="utf-8")) or {}
    items = cfg.get("items") or []

    lines = [
        "// AUTO-GENERATED from ~/Dev/configs/menus/sites/website.yaml",
        "// Edit the yaml; this file is regenerated by scripts/sync-menu.py (prebuild hook).",
        "",
        "export const navigationConfig = [",
    ]
    for it in items:
        name = json.dumps(it["name"], ensure_ascii=False)
        path = json.dumps(it["path"], ensure_ascii=False)
        if it.get("external"):
            lines.append(f"  {{ name: {name}, path: {path}, external: true }},")
        else:
            lines.append(f"  {{ name: {name}, path: {path} }},")
    lines.append("]")
    lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT.relative_to(REPO)} ({len(items)} items)")


if __name__ == "__main__":
    main()
