#!/usr/bin/env python3
"""website 服务页 catalog 同步：menus.py build-catalog → lib/catalog.generated.ts

由 prebuild / predev hook 触发；也可手动跑：
  python3 scripts/sync-catalog.py

数据流：
  ~/Dev/website/lib/services.ts  ─┐
  ~/Dev/tools/configs/menus/sites/*    ─┼─→ menus.py build-catalog
  ~/Dev/tools/configs/menus/navbar.yaml ┘             │
                                                ▼
                              lib/catalog.generated.ts
                                                │
                                                ▼
                          /services 页消费的本地工具/项目目录

消费者：components/local-catalog.tsx import { CATALOG } from "@/lib/catalog.generated"
"""
import json
import subprocess
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("ERROR: 需要 PyYAML。安装：pip3 install pyyaml", file=sys.stderr)
    sys.exit(2)

REPO = Path(__file__).parent.parent
MENUS_TOOL = Path.home() / "Dev" / "devtools" / "lib" / "tools" / "menus.py"
OUT = REPO / "lib" / "catalog.generated.ts"


def main():
    if not MENUS_TOOL.exists():
        print(f"ERROR: {MENUS_TOOL} not found", file=sys.stderr)
        sys.exit(1)

    proc = subprocess.run(
        [sys.executable, str(MENUS_TOOL), "build-catalog"],
        capture_output=True, text=True, check=False,
    )
    if proc.returncode != 0:
        print(f"ERROR: menus.py build-catalog failed:\n{proc.stderr}", file=sys.stderr)
        sys.exit(1)

    catalog = yaml.safe_load(proc.stdout) or {}
    entries = catalog.get("entries") or []

    catalog_json = json.dumps(catalog, ensure_ascii=False, indent=2)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    new_content = (
        "// AUTO-GENERATED from ~/Dev/tools/configs/menus/ (via menus.py build-catalog)\n"
        "// Edit the source yaml; this file is regenerated by scripts/sync-catalog.py.\n"
        "\n"
        "export interface CatalogSubPage { label: string; path: string }\n"
        "export interface CatalogLink { label: string; url: string }\n"
        "export interface CatalogEntry {\n"
        "  id: string\n"
        "  type:\n"
        "    | 'subdomain' | 'vps-only' | 'tool-lib' | 'raycast-wrapper'\n"
        "    | 'config-repo' | 'knowledge' | 'app-candidate' | 'archived' | 'dormant'\n"
        "  name?: string\n"
        "  subdomain?: string\n"
        "  url?: string\n"
        "  port?: number\n"
        "  access_type?: 'public' | 'cf-access'\n"
        "  group?: string\n"
        "  description?: string\n"
        "  source?: string\n"
        "  path?: string\n"
        "  stack?: string[]\n"
        "  status?: string\n"
        "  sub_pages?: CatalogSubPage[]\n"
        "  links?: CatalogLink[]\n"
        "}\n"
        "\n"
        f"export const CATALOG = ({catalog_json}) as {{\n"
        "  meta: { generated_at: string; sources: string[] }\n"
        "  entries: CatalogEntry[]\n"
        "}\n"
    )

    # Skip write if only generated_at changed (avoid timestamp-only churn).
    import re as _re
    _strip_ts = lambda s: _re.sub(r'"generated_at": "[^"]+"', '"generated_at": ""', s)
    if OUT.exists() and _strip_ts(OUT.read_text(encoding="utf-8")) == _strip_ts(new_content):
        print(f"Unchanged {OUT.relative_to(REPO)} ({len(entries)} entries)")
        return
    OUT.write_text(new_content, encoding="utf-8")
    print(f"Wrote {OUT.relative_to(REPO)} ({len(entries)} entries)")


if __name__ == "__main__":
    main()
