#!/usr/bin/env python3
"""website 主导航 + 顶行共享 navbar 同步。

  python3 scripts/sync-menu.py

数据流：
  ~/Dev/tools/configs/menus/sites/website.yaml  →  lib/menu.generated.ts (主站第二行 5 项)
  ~/Dev/tools/configs/menus/navbar.yaml         →  lib/shared-navbar.generated.ts (主站第一行)
                                              （由 menus.py build-website-navbar 生成）
"""
import json
import subprocess
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("ERROR: 需要 PyYAML。安装：pip3 install pyyaml", file=sys.stderr)
    sys.exit(2)

REPO = Path(__file__).parent.parent
SITE_YAML = Path.home() / "Dev" / "tools" / "configs" / "menus" / "sites" / "website.yaml"
MENUS_TOOL = Path.home() / "Dev" / "devtools" / "lib" / "tools" / "menus.py"
OUT_INTERNAL = REPO / "lib" / "menu.generated.ts"


def gen_internal_nav():
    if not SITE_YAML.exists():
        print(f"ERROR: {SITE_YAML} not found", file=sys.stderr)
        sys.exit(1)
    cfg = yaml.safe_load(SITE_YAML.read_text(encoding="utf-8")) or {}
    items = cfg.get("items") or []

    lines = [
        "// AUTO-GENERATED from ~/Dev/tools/configs/menus/sites/website.yaml",
        "// Edit the yaml; this file is regenerated by scripts/sync-menu.py (prebuild hook).",
        "",
        "export const navigationConfig = [",
    ]
    for it in items:
        name = json.dumps(it["name"], ensure_ascii=False)
        path = json.dumps(it["path"], ensure_ascii=False)
        if it.get("external"):
            lines.append(f"  {{ name: {name}, path: {path}, external: true }},")
        else:
            lines.append(f"  {{ name: {name}, path: {path} }},")
    lines.append("]")
    lines.append("")

    OUT_INTERNAL.parent.mkdir(parents=True, exist_ok=True)
    OUT_INTERNAL.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT_INTERNAL.relative_to(REPO)} ({len(items)} items)")


def gen_shared_navbar():
    """Delegate to menus.py — single source of truth for the renderer."""
    if not MENUS_TOOL.exists():
        print(f"WARN: {MENUS_TOOL} not found, skipping shared-navbar generation", file=sys.stderr)
        return
    proc = subprocess.run(
        [sys.executable, str(MENUS_TOOL), "build-website-navbar", "-w"],
        capture_output=True, text=True, check=False,
    )
    if proc.returncode != 0:
        print(f"ERROR: menus.py build-website-navbar failed:\n{proc.stderr}", file=sys.stderr)
        sys.exit(1)
    # echo the success line
    sys.stdout.write(proc.stdout)


def main():
    gen_internal_nav()
    gen_shared_navbar()


if __name__ == "__main__":
    main()
